; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "TheGuideToTheNewEden"
!define PRODUCT_VERSION "3.0.1.0"
!define PRODUCT_PUBLISHER "QEDSD"
!define PRODUCT_WEB_SITE "https://github.com/qedsd/TheGuideToTheNewEden"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\TheGuideToTheNewEden.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; .NET 9.0 Desktop Runtime required version
!define DOTNET_REQUIRED_VERSION "9.0"

; MUI 1.67 compatible ------
!include "MUI.nsh"
!include "LogicLib.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "D:\QEDSD\Code\TheGuideToTheNewEden\TheGuideToTheNewEden\TheGuideToTheNewEden.WinUI\TheGuideToTheNewEden.WinUI\bin\x64\Release\net9.0-windows10.0.19041.0\win-x64\logo.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "TheGuideToTheNewEden"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\TheGuideToTheNewEden.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "TheGuideToTheNewEden.exe"
InstallDir "$PROGRAMFILES\TheGuideToTheNewEden"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

; Check .NET Desktop Runtime 9.0
Function CheckDotNetRuntime
  Push $0
  ReadRegStr $0 HKLM "SOFTWARE\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App" "${DOTNET_REQUIRED_VERSION}"
  ${If} $0 == ""
    ReadRegStr $0 HKLM "SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.NETCore.App" "${DOTNET_REQUIRED_VERSION}"
  ${EndIf}
  ${If} $0 == ""
    MessageBox MB_YESNO|MB_ICONEXCLAMATION \
      "$(^Name) requires .NET Desktop Runtime ${DOTNET_REQUIRED_VERSION}.$\n$\nDownload and install it now?" \
      IDYES +2
    Abort "Setup cancelled because .NET Runtime is missing."
    ExecShell "open" "https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-${DOTNET_REQUIRED_VERSION}-windows-x64-installer"
    Abort "Please re-run Setup after installing .NET Runtime."
  ${EndIf}
  Pop $0
FunctionEnd

; Check Windows App SDK Runtime (via WindowsAppRuntime version)
Function CheckWindowsAppSDK
  Push $0
  Push $1
  Push $2
  StrCpy $2 "0"
  ; Check for Windows App SDK Runtime 1.6+ (which supports WinAppSDK 2.x)
  ReadRegStr $0 HKLM "SOFTWARE\Microsoft\WindowsAppRuntime\1.6" "Version"
  ${If} $0 != ""
    StrCpy $2 "1"
  ${EndIf}
  ${If} $2 == "0"
    ; Fallback: check for any Windows App SDK Runtime
    EnumRegKey $0 HKLM "SOFTWARE\Microsoft\WindowsAppRuntime" 0
    ${If} $0 != ""
      StrCpy $2 "1"
    ${EndIf}
  ${EndIf}
  ${If} $2 == "0"
    MessageBox MB_YESNO|MB_ICONEXCLAMATION \
      "$(^Name) requires Windows App SDK Runtime.$\n$\nDownload and install it now?" \
      IDYES +2
    Abort "Setup cancelled because Windows App SDK Runtime is missing."
    ExecShell "open" "https://aka.ms/windowsappsdk/stable-msixinstaller-x64"
    Abort "Please re-run Setup after installing Windows App SDK Runtime."
  ${EndIf}
  Pop $2
  Pop $1
  Pop $0
FunctionEnd

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
  Call CheckDotNetRuntime
  Call CheckWindowsAppSDK
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File /r "D:\QEDSD\Code\TheGuideToTheNewEden\TheGuideToTheNewEden\TheGuideToTheNewEden.WinUI\TheGuideToTheNewEden.WinUI\bin\x64\Release\net9.0-windows10.0.19041.0\win-x64\*.*"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\TheGuideToTheNewEden.lnk" "$INSTDIR\TheGuideToTheNewEden.exe"
  CreateShortCut "$DESKTOP\TheGuideToTheNewEden.lnk" "$INSTDIR\TheGuideToTheNewEden.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\TheGuideToTheNewEden.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\TheGuideToTheNewEden.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$DESKTOP\TheGuideToTheNewEden.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\TheGuideToTheNewEden.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir /r "$INSTDIR\*.*"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  DeleteRegKey HKCR "eveauth-qedsd-neweden3"
  SetAutoClose true
SectionEnd

Section "Protocol"
    WriteRegStr HKCR "eveauth-qedsd-neweden3" "URL Protocol" ''
    WriteRegStr HKCR "eveauth-qedsd-neweden3\shell\open\command" "" '"$INSTDIR\TheGuideToTheNewEden.exe" "%1"'

SectionEnd
